# --- General options --- #

# Name of website
title: The Atlas
# Short description of your site
description: Mapping the Histories and Metadata of Digitised Newspapers Collections Around the World

# Build settings
markdown: CommonMarkGhPages

# url is the the website domain URL without a trailing slash
url: "https://www.digitisednewspapers.net"

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About the Atlas:
    - The Project: "introduction/project"
    - Methodology:  "introduction/methodology"
    - Aims and Objectives:  "introduction/aims"
    - Acknowledgements:  "introduction/acknowledgements"
    - Latest News: "news"
  Databases: 
    - Introduction: "histories"
    - British Library: "histories/bl" 
    - Chronicling America: "histories/ca" 
    - Delpher: "histories/delpher" 
    - Europeana: "histories/europeana"  
    - Hemeroteca Nacional: "histories/hndm" 
    - Papers Past: "histories/pp" 
    - Suomen Kansalliskirjaston: "histories/nlf"
    - Times Digital Archive: "histories/tda"
    - Trove: "histories/trove"
    - ZEFYS: "histories/slb" 
  Metadata Maps: 
    - Introduction: "maps"
    - Content: "maps/content"
    - Citation: "maps/citation"
    - Bibliographic: "maps/bibliographic"
    - Holdings: "maps/holdings"
    - Descriptive: "maps/descriptive"
    - User-Generated: "maps/social"
    - Technical: "maps/technical"
  Resources: 
    - Abbreviations: "introduction/abbreviations"
    - Bibliography: "introduction/bibliography"
    - Downloads: "introduction/citation"
    - Glossary: "glossary"
    - Timeline: "introduction/timeline"
    - Web Resources: "introduction/web"
    
# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "img/atlaslogo.png"

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

#navbar-col: "#45ADA8"
#navbar-text-col: "#373737"
navbar-children-col: "#FFFFFF"

#page-col: "#594F4"

#link-col: "#805b54"
#hover-col: "#805b54"

#footer-col: "#45ADA8"
#footer-text-col: "#373737"
#footer-link-col: "#373737"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

#navbar-img: "/img/sunrise.jpg"
# footer-img: "/img/sunrise.jpg"
# page-img: "/img/sunrise.jpg"

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "UA-157422555-1"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-157422555-1"

# Google Tag Manager ID
#gtm: ""

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Oceanic Exchanges

# Select your active Social Network Links.
social-network-links:
  rss: true
  email: "m.h.beals@lboro.ac.uk"
  github: AtlasOfDigitisedNewspapers/AtlasOfDigitisedNewspapers.github.io
  twitter: oceanicex

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format
date_format: "%B %-d, %Y"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
paginate_path: "/news/page:num/"

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
